package bipin.advent;

public class TwentyTwentyOne_Day2 {

    public static void main(String[] args) {
        Integer horizontalPosition = 0;
        Integer depth = 0;
        Integer aim = 0;
        String[] inputArray = input.split(System.lineSeparator());
        for(String movement: inputArray) {
            String[] mvSp = movement.split(" ");
            String direction = mvSp[0];
            Integer distance = Integer.parseInt(mvSp[1]);
            switch (direction) {
                case "forward":
                    horizontalPosition += distance;
                    depth += (aim * distance);
                    break;

                case "up":
//                    depth -= distance;
                    aim -= distance;
                    break;

                case "down":
//                    depth += distance;
                    aim += distance;
                    break;
            }
        }
        System.out.println("Horizontal Position: " + horizontalPosition + " Depth: " + depth);
        System.out.println("Multiplied answer: " + (horizontalPosition * depth));
    }

static String testInput = "forward 5\n" +
        "down 5\n" +
        "forward 8\n" +
        "up 3\n" +
        "down 8\n" +
        "forward 2";
    static String input = "forward 8\n" +
            "forward 9\n" +
            "forward 9\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 1\n" +
            "down 7\n" +
            "down 7\n" +
            "down 4\n" +
            "down 2\n" +
            "down 6\n" +
            "down 6\n" +
            "down 2\n" +
            "forward 6\n" +
            "forward 6\n" +
            "forward 2\n" +
            "forward 2\n" +
            "forward 7\n" +
            "forward 6\n" +
            "up 6\n" +
            "up 8\n" +
            "forward 5\n" +
            "forward 4\n" +
            "down 6\n" +
            "forward 7\n" +
            "down 5\n" +
            "forward 5\n" +
            "down 8\n" +
            "down 8\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 2\n" +
            "forward 7\n" +
            "up 8\n" +
            "forward 3\n" +
            "down 2\n" +
            "forward 1\n" +
            "up 3\n" +
            "forward 3\n" +
            "up 1\n" +
            "down 3\n" +
            "up 7\n" +
            "up 2\n" +
            "down 4\n" +
            "down 2\n" +
            "forward 9\n" +
            "forward 3\n" +
            "down 8\n" +
            "forward 5\n" +
            "up 9\n" +
            "up 4\n" +
            "forward 9\n" +
            "down 1\n" +
            "forward 6\n" +
            "down 3\n" +
            "forward 8\n" +
            "up 2\n" +
            "forward 3\n" +
            "up 7\n" +
            "down 4\n" +
            "forward 2\n" +
            "forward 7\n" +
            "forward 3\n" +
            "down 1\n" +
            "down 3\n" +
            "up 5\n" +
            "forward 6\n" +
            "down 5\n" +
            "down 4\n" +
            "down 8\n" +
            "down 2\n" +
            "up 5\n" +
            "forward 7\n" +
            "up 8\n" +
            "forward 2\n" +
            "down 5\n" +
            "forward 3\n" +
            "up 1\n" +
            "up 5\n" +
            "down 8\n" +
            "down 3\n" +
            "forward 4\n" +
            "forward 4\n" +
            "forward 1\n" +
            "up 8\n" +
            "down 9\n" +
            "forward 7\n" +
            "forward 9\n" +
            "down 5\n" +
            "up 3\n" +
            "down 9\n" +
            "up 6\n" +
            "forward 1\n" +
            "forward 3\n" +
            "forward 5\n" +
            "down 5\n" +
            "forward 6\n" +
            "down 3\n" +
            "down 8\n" +
            "forward 3\n" +
            "forward 5\n" +
            "forward 7\n" +
            "forward 6\n" +
            "down 9\n" +
            "down 5\n" +
            "down 6\n" +
            "down 5\n" +
            "down 1\n" +
            "down 8\n" +
            "forward 3\n" +
            "down 9\n" +
            "down 5\n" +
            "down 5\n" +
            "forward 9\n" +
            "forward 2\n" +
            "down 7\n" +
            "forward 9\n" +
            "forward 9\n" +
            "up 1\n" +
            "forward 3\n" +
            "up 9\n" +
            "forward 5\n" +
            "forward 7\n" +
            "down 7\n" +
            "forward 2\n" +
            "up 8\n" +
            "up 6\n" +
            "down 7\n" +
            "down 3\n" +
            "down 5\n" +
            "down 2\n" +
            "forward 6\n" +
            "forward 6\n" +
            "up 6\n" +
            "up 2\n" +
            "forward 4\n" +
            "forward 7\n" +
            "forward 1\n" +
            "down 4\n" +
            "up 8\n" +
            "down 3\n" +
            "up 1\n" +
            "down 2\n" +
            "forward 4\n" +
            "forward 7\n" +
            "up 1\n" +
            "down 7\n" +
            "forward 8\n" +
            "up 2\n" +
            "down 8\n" +
            "up 4\n" +
            "up 4\n" +
            "up 2\n" +
            "down 8\n" +
            "up 4\n" +
            "down 6\n" +
            "up 8\n" +
            "down 5\n" +
            "up 5\n" +
            "down 8\n" +
            "forward 9\n" +
            "down 1\n" +
            "down 5\n" +
            "forward 3\n" +
            "forward 3\n" +
            "up 9\n" +
            "down 2\n" +
            "forward 3\n" +
            "down 6\n" +
            "forward 1\n" +
            "forward 9\n" +
            "forward 3\n" +
            "down 8\n" +
            "up 4\n" +
            "down 1\n" +
            "down 8\n" +
            "up 1\n" +
            "forward 2\n" +
            "down 7\n" +
            "up 3\n" +
            "up 8\n" +
            "down 2\n" +
            "up 6\n" +
            "forward 6\n" +
            "down 9\n" +
            "forward 4\n" +
            "forward 7\n" +
            "up 9\n" +
            "forward 3\n" +
            "forward 2\n" +
            "down 8\n" +
            "down 2\n" +
            "down 5\n" +
            "down 5\n" +
            "down 1\n" +
            "up 7\n" +
            "down 4\n" +
            "forward 5\n" +
            "down 9\n" +
            "down 5\n" +
            "down 1\n" +
            "down 6\n" +
            "forward 9\n" +
            "down 6\n" +
            "forward 3\n" +
            "down 3\n" +
            "up 6\n" +
            "forward 2\n" +
            "forward 6\n" +
            "down 2\n" +
            "down 9\n" +
            "down 6\n" +
            "down 1\n" +
            "down 7\n" +
            "down 6\n" +
            "down 6\n" +
            "up 1\n" +
            "forward 8\n" +
            "down 9\n" +
            "down 6\n" +
            "down 8\n" +
            "down 8\n" +
            "down 6\n" +
            "down 3\n" +
            "forward 9\n" +
            "forward 6\n" +
            "down 9\n" +
            "forward 5\n" +
            "down 6\n" +
            "down 6\n" +
            "down 9\n" +
            "down 7\n" +
            "down 3\n" +
            "forward 1\n" +
            "up 9\n" +
            "forward 9\n" +
            "down 7\n" +
            "forward 4\n" +
            "down 1\n" +
            "forward 9\n" +
            "up 9\n" +
            "down 7\n" +
            "forward 5\n" +
            "down 3\n" +
            "up 7\n" +
            "forward 9\n" +
            "forward 6\n" +
            "forward 3\n" +
            "forward 8\n" +
            "down 4\n" +
            "down 1\n" +
            "down 7\n" +
            "down 7\n" +
            "up 4\n" +
            "down 9\n" +
            "forward 6\n" +
            "forward 7\n" +
            "down 8\n" +
            "forward 2\n" +
            "forward 2\n" +
            "forward 9\n" +
            "forward 6\n" +
            "forward 9\n" +
            "up 6\n" +
            "up 8\n" +
            "forward 2\n" +
            "up 3\n" +
            "forward 9\n" +
            "forward 1\n" +
            "down 4\n" +
            "forward 8\n" +
            "down 4\n" +
            "forward 5\n" +
            "forward 7\n" +
            "up 2\n" +
            "forward 5\n" +
            "down 4\n" +
            "forward 3\n" +
            "down 5\n" +
            "forward 9\n" +
            "up 3\n" +
            "forward 8\n" +
            "down 7\n" +
            "down 7\n" +
            "down 9\n" +
            "forward 2\n" +
            "down 1\n" +
            "down 6\n" +
            "up 8\n" +
            "down 2\n" +
            "down 1\n" +
            "up 3\n" +
            "down 3\n" +
            "forward 2\n" +
            "forward 6\n" +
            "up 6\n" +
            "down 3\n" +
            "up 9\n" +
            "up 3\n" +
            "down 8\n" +
            "up 6\n" +
            "down 2\n" +
            "forward 4\n" +
            "up 1\n" +
            "down 5\n" +
            "down 4\n" +
            "up 9\n" +
            "up 7\n" +
            "forward 7\n" +
            "down 9\n" +
            "forward 9\n" +
            "forward 5\n" +
            "forward 3\n" +
            "down 4\n" +
            "up 6\n" +
            "up 7\n" +
            "down 7\n" +
            "down 6\n" +
            "up 9\n" +
            "up 4\n" +
            "down 7\n" +
            "forward 7\n" +
            "forward 8\n" +
            "down 9\n" +
            "forward 5\n" +
            "forward 4\n" +
            "down 5\n" +
            "forward 8\n" +
            "forward 5\n" +
            "up 3\n" +
            "down 9\n" +
            "forward 1\n" +
            "forward 2\n" +
            "up 3\n" +
            "down 2\n" +
            "down 1\n" +
            "forward 5\n" +
            "forward 5\n" +
            "forward 6\n" +
            "up 2\n" +
            "forward 3\n" +
            "down 7\n" +
            "down 6\n" +
            "up 3\n" +
            "down 4\n" +
            "down 4\n" +
            "forward 5\n" +
            "down 3\n" +
            "up 6\n" +
            "forward 1\n" +
            "up 8\n" +
            "forward 7\n" +
            "forward 1\n" +
            "forward 9\n" +
            "down 2\n" +
            "up 8\n" +
            "up 1\n" +
            "up 4\n" +
            "forward 9\n" +
            "forward 3\n" +
            "forward 5\n" +
            "down 1\n" +
            "up 9\n" +
            "down 1\n" +
            "forward 3\n" +
            "down 6\n" +
            "down 8\n" +
            "up 4\n" +
            "forward 6\n" +
            "up 7\n" +
            "down 8\n" +
            "forward 9\n" +
            "up 2\n" +
            "down 7\n" +
            "down 1\n" +
            "forward 9\n" +
            "up 7\n" +
            "forward 3\n" +
            "forward 9\n" +
            "forward 1\n" +
            "forward 1\n" +
            "down 9\n" +
            "forward 1\n" +
            "up 4\n" +
            "down 5\n" +
            "forward 4\n" +
            "down 1\n" +
            "forward 4\n" +
            "forward 9\n" +
            "up 4\n" +
            "down 3\n" +
            "down 6\n" +
            "up 2\n" +
            "down 6\n" +
            "down 5\n" +
            "forward 5\n" +
            "up 1\n" +
            "up 9\n" +
            "forward 8\n" +
            "up 3\n" +
            "down 1\n" +
            "forward 3\n" +
            "forward 7\n" +
            "up 6\n" +
            "up 3\n" +
            "down 6\n" +
            "forward 7\n" +
            "up 6\n" +
            "down 7\n" +
            "forward 8\n" +
            "up 4\n" +
            "down 8\n" +
            "up 9\n" +
            "up 3\n" +
            "down 3\n" +
            "forward 8\n" +
            "down 4\n" +
            "down 9\n" +
            "forward 2\n" +
            "down 7\n" +
            "up 1\n" +
            "forward 9\n" +
            "forward 5\n" +
            "up 8\n" +
            "forward 9\n" +
            "forward 4\n" +
            "forward 9\n" +
            "forward 7\n" +
            "down 4\n" +
            "up 4\n" +
            "down 7\n" +
            "down 4\n" +
            "down 4\n" +
            "down 1\n" +
            "forward 5\n" +
            "forward 4\n" +
            "down 1\n" +
            "down 4\n" +
            "down 8\n" +
            "down 3\n" +
            "forward 7\n" +
            "forward 4\n" +
            "down 1\n" +
            "down 9\n" +
            "up 3\n" +
            "forward 2\n" +
            "down 8\n" +
            "down 9\n" +
            "down 2\n" +
            "down 5\n" +
            "up 9\n" +
            "down 9\n" +
            "up 9\n" +
            "forward 5\n" +
            "forward 8\n" +
            "forward 9\n" +
            "down 5\n" +
            "forward 6\n" +
            "down 8\n" +
            "down 9\n" +
            "forward 8\n" +
            "up 5\n" +
            "up 9\n" +
            "up 7\n" +
            "up 8\n" +
            "forward 9\n" +
            "forward 1\n" +
            "up 6\n" +
            "down 8\n" +
            "down 8\n" +
            "forward 1\n" +
            "up 1\n" +
            "forward 8\n" +
            "forward 6\n" +
            "down 4\n" +
            "forward 1\n" +
            "down 7\n" +
            "forward 8\n" +
            "forward 3\n" +
            "up 3\n" +
            "down 4\n" +
            "down 2\n" +
            "forward 2\n" +
            "forward 3\n" +
            "up 4\n" +
            "down 3\n" +
            "forward 2\n" +
            "down 8\n" +
            "forward 7\n" +
            "up 3\n" +
            "down 2\n" +
            "forward 2\n" +
            "down 5\n" +
            "up 6\n" +
            "up 6\n" +
            "forward 4\n" +
            "up 4\n" +
            "down 8\n" +
            "forward 8\n" +
            "down 9\n" +
            "down 9\n" +
            "down 6\n" +
            "down 2\n" +
            "forward 2\n" +
            "up 6\n" +
            "up 5\n" +
            "forward 3\n" +
            "forward 3\n" +
            "up 9\n" +
            "down 3\n" +
            "forward 8\n" +
            "down 5\n" +
            "forward 5\n" +
            "forward 7\n" +
            "down 3\n" +
            "down 4\n" +
            "down 1\n" +
            "down 8\n" +
            "down 1\n" +
            "down 1\n" +
            "forward 9\n" +
            "forward 3\n" +
            "down 8\n" +
            "down 6\n" +
            "up 9\n" +
            "forward 1\n" +
            "forward 5\n" +
            "up 9\n" +
            "up 8\n" +
            "forward 2\n" +
            "up 8\n" +
            "down 9\n" +
            "up 2\n" +
            "forward 5\n" +
            "forward 1\n" +
            "forward 8\n" +
            "down 3\n" +
            "forward 4\n" +
            "down 5\n" +
            "up 6\n" +
            "forward 8\n" +
            "forward 9\n" +
            "forward 3\n" +
            "down 1\n" +
            "down 3\n" +
            "down 3\n" +
            "up 4\n" +
            "forward 9\n" +
            "down 3\n" +
            "down 6\n" +
            "forward 3\n" +
            "forward 2\n" +
            "down 6\n" +
            "down 8\n" +
            "forward 6\n" +
            "up 8\n" +
            "up 3\n" +
            "up 4\n" +
            "forward 2\n" +
            "forward 4\n" +
            "forward 4\n" +
            "forward 7\n" +
            "down 6\n" +
            "up 8\n" +
            "down 3\n" +
            "forward 8\n" +
            "forward 4\n" +
            "down 7\n" +
            "down 5\n" +
            "forward 6\n" +
            "forward 4\n" +
            "forward 6\n" +
            "down 3\n" +
            "forward 3\n" +
            "down 1\n" +
            "down 7\n" +
            "forward 3\n" +
            "forward 2\n" +
            "forward 7\n" +
            "down 5\n" +
            "up 4\n" +
            "down 6\n" +
            "down 9\n" +
            "forward 3\n" +
            "forward 5\n" +
            "forward 3\n" +
            "down 1\n" +
            "forward 2\n" +
            "up 5\n" +
            "up 6\n" +
            "forward 2\n" +
            "down 4\n" +
            "forward 3\n" +
            "down 4\n" +
            "down 1\n" +
            "forward 8\n" +
            "up 2\n" +
            "down 3\n" +
            "down 6\n" +
            "up 5\n" +
            "forward 3\n" +
            "forward 6\n" +
            "down 3\n" +
            "forward 1\n" +
            "down 7\n" +
            "forward 2\n" +
            "forward 1\n" +
            "forward 6\n" +
            "forward 5\n" +
            "forward 3\n" +
            "down 4\n" +
            "down 8\n" +
            "forward 1\n" +
            "up 2\n" +
            "up 8\n" +
            "down 4\n" +
            "forward 9\n" +
            "up 6\n" +
            "forward 5\n" +
            "forward 7\n" +
            "down 5\n" +
            "forward 5\n" +
            "down 1\n" +
            "forward 4\n" +
            "forward 5\n" +
            "up 2\n" +
            "forward 5\n" +
            "up 8\n" +
            "up 1\n" +
            "forward 2\n" +
            "down 4\n" +
            "down 6\n" +
            "forward 4\n" +
            "down 2\n" +
            "down 3\n" +
            "forward 2\n" +
            "up 3\n" +
            "up 4\n" +
            "forward 2\n" +
            "down 6\n" +
            "forward 1\n" +
            "forward 4\n" +
            "down 6\n" +
            "forward 7\n" +
            "up 2\n" +
            "forward 7\n" +
            "forward 6\n" +
            "up 2\n" +
            "forward 8\n" +
            "forward 4\n" +
            "forward 9\n" +
            "down 1\n" +
            "down 8\n" +
            "forward 3\n" +
            "forward 2\n" +
            "down 8\n" +
            "up 1\n" +
            "forward 4\n" +
            "down 8\n" +
            "forward 2\n" +
            "forward 8\n" +
            "up 2\n" +
            "down 1\n" +
            "forward 4\n" +
            "forward 2\n" +
            "up 4\n" +
            "up 2\n" +
            "down 3\n" +
            "up 8\n" +
            "forward 3\n" +
            "up 8\n" +
            "forward 9\n" +
            "up 1\n" +
            "up 5\n" +
            "down 5\n" +
            "down 6\n" +
            "forward 1\n" +
            "up 5\n" +
            "up 8\n" +
            "forward 7\n" +
            "down 5\n" +
            "up 4\n" +
            "forward 2\n" +
            "up 4\n" +
            "up 4\n" +
            "down 2\n" +
            "forward 6\n" +
            "forward 2\n" +
            "down 7\n" +
            "down 5\n" +
            "forward 1\n" +
            "down 2\n" +
            "down 5\n" +
            "down 7\n" +
            "up 8\n" +
            "down 8\n" +
            "up 5\n" +
            "down 1\n" +
            "forward 5\n" +
            "down 2\n" +
            "forward 5\n" +
            "down 1\n" +
            "up 7\n" +
            "up 2\n" +
            "forward 2\n" +
            "forward 3\n" +
            "forward 6\n" +
            "forward 3\n" +
            "down 8\n" +
            "up 8\n" +
            "forward 8\n" +
            "forward 1\n" +
            "forward 7\n" +
            "up 2\n" +
            "forward 9\n" +
            "down 1\n" +
            "forward 5\n" +
            "up 9\n" +
            "forward 3\n" +
            "forward 7\n" +
            "forward 8\n" +
            "up 1\n" +
            "down 3\n" +
            "forward 5\n" +
            "down 2\n" +
            "forward 6\n" +
            "forward 3\n" +
            "down 9\n" +
            "up 5\n" +
            "forward 2\n" +
            "down 4\n" +
            "up 1\n" +
            "forward 4\n" +
            "up 4\n" +
            "down 8\n" +
            "down 8\n" +
            "forward 3\n" +
            "forward 8\n" +
            "down 7\n" +
            "up 3\n" +
            "forward 1\n" +
            "up 3\n" +
            "forward 9\n" +
            "forward 7\n" +
            "forward 1\n" +
            "down 6\n" +
            "forward 3\n" +
            "down 1\n" +
            "down 8\n" +
            "forward 5\n" +
            "forward 3\n" +
            "up 6\n" +
            "forward 5\n" +
            "forward 4\n" +
            "forward 3\n" +
            "forward 9\n" +
            "forward 8\n" +
            "down 6\n" +
            "down 2\n" +
            "forward 7\n" +
            "forward 6\n" +
            "up 6\n" +
            "down 6\n" +
            "down 4\n" +
            "down 3\n" +
            "forward 8\n" +
            "down 9\n" +
            "up 5\n" +
            "forward 3\n" +
            "forward 2\n" +
            "down 5\n" +
            "up 4\n" +
            "down 6\n" +
            "down 3\n" +
            "forward 9\n" +
            "down 2\n" +
            "forward 9\n" +
            "forward 8\n" +
            "up 1\n" +
            "down 2\n" +
            "forward 7\n" +
            "up 5\n" +
            "up 6\n" +
            "down 8\n" +
            "up 9\n" +
            "up 8\n" +
            "forward 1\n" +
            "forward 5\n" +
            "down 9\n" +
            "forward 8\n" +
            "down 8\n" +
            "up 1\n" +
            "down 7\n" +
            "forward 7\n" +
            "up 3\n" +
            "down 3\n" +
            "down 1\n" +
            "forward 2\n" +
            "down 3\n" +
            "forward 9\n" +
            "forward 2\n" +
            "down 8\n" +
            "down 2\n" +
            "forward 5\n" +
            "down 9\n" +
            "down 1\n" +
            "down 5\n" +
            "down 6\n" +
            "up 4\n" +
            "up 3\n" +
            "down 1\n" +
            "up 7\n" +
            "forward 6\n" +
            "down 3\n" +
            "down 6\n" +
            "up 5\n" +
            "forward 8\n" +
            "up 8\n" +
            "down 1\n" +
            "down 2\n" +
            "up 8\n" +
            "down 7\n" +
            "forward 7\n" +
            "forward 4\n" +
            "down 8\n" +
            "down 3\n" +
            "forward 3\n" +
            "down 4\n" +
            "forward 3\n" +
            "down 6\n" +
            "forward 4\n" +
            "forward 7\n" +
            "forward 9\n" +
            "up 7\n" +
            "forward 1\n" +
            "down 7\n" +
            "down 8\n" +
            "down 8\n" +
            "up 6\n" +
            "down 3\n" +
            "forward 5\n" +
            "forward 5\n" +
            "forward 9\n" +
            "forward 4\n" +
            "down 4\n" +
            "down 8\n" +
            "down 7\n" +
            "down 1\n" +
            "forward 2\n" +
            "forward 4\n" +
            "down 3\n" +
            "down 6\n" +
            "down 7\n" +
            "forward 5\n" +
            "down 8\n" +
            "down 1\n" +
            "forward 4\n" +
            "forward 3\n" +
            "forward 1\n" +
            "down 6\n" +
            "down 7\n" +
            "down 1\n" +
            "forward 6\n" +
            "down 4\n" +
            "up 2\n" +
            "forward 4\n" +
            "down 2\n" +
            "up 5\n" +
            "down 2\n" +
            "down 6\n" +
            "up 7\n" +
            "forward 4\n" +
            "forward 7\n" +
            "forward 9\n" +
            "up 5\n" +
            "down 9\n" +
            "up 5\n" +
            "forward 6\n" +
            "down 2\n" +
            "up 8\n" +
            "up 9\n" +
            "up 9\n" +
            "forward 5\n" +
            "down 2\n" +
            "forward 2\n" +
            "down 7\n" +
            "forward 5\n" +
            "forward 9\n" +
            "up 8\n" +
            "down 8\n" +
            "forward 1\n" +
            "down 2\n" +
            "up 3\n" +
            "forward 3\n" +
            "down 5\n" +
            "forward 4\n" +
            "down 3\n" +
            "forward 4\n" +
            "forward 9\n" +
            "forward 3\n" +
            "down 5\n" +
            "forward 4\n" +
            "down 2\n" +
            "forward 5\n" +
            "forward 8\n" +
            "up 6\n" +
            "up 2\n" +
            "down 3\n" +
            "forward 6\n" +
            "down 5\n" +
            "down 4\n" +
            "down 4\n" +
            "down 4\n" +
            "up 2\n" +
            "up 2\n" +
            "forward 6\n" +
            "forward 2\n" +
            "forward 9\n" +
            "down 2\n" +
            "down 9\n" +
            "down 8\n" +
            "forward 2\n" +
            "down 3\n" +
            "up 3\n" +
            "forward 5\n" +
            "down 4\n" +
            "up 3\n" +
            "forward 3\n" +
            "down 1\n" +
            "forward 7\n" +
            "forward 5\n" +
            "forward 6\n" +
            "down 8\n" +
            "down 5\n" +
            "down 5\n" +
            "down 9\n" +
            "up 2\n" +
            "forward 3\n" +
            "down 4\n" +
            "down 9\n" +
            "forward 3\n" +
            "forward 9\n" +
            "forward 2\n" +
            "forward 4\n" +
            "up 6\n" +
            "down 6\n" +
            "up 9\n" +
            "forward 8\n" +
            "down 7\n" +
            "forward 1\n" +
            "forward 4\n" +
            "up 1\n" +
            "up 2\n" +
            "down 9\n" +
            "forward 6\n" +
            "down 6\n" +
            "down 1\n" +
            "down 4\n" +
            "down 7\n" +
            "down 6\n" +
            "forward 5\n" +
            "up 1\n" +
            "up 7\n" +
            "down 2\n" +
            "down 8\n" +
            "down 2\n" +
            "down 7\n" +
            "down 3\n" +
            "up 9\n" +
            "down 7\n" +
            "down 5\n" +
            "down 6\n" +
            "forward 9\n" +
            "up 3\n" +
            "forward 2\n" +
            "down 8\n" +
            "forward 4\n" +
            "down 6\n" +
            "forward 3\n" +
            "up 3\n" +
            "down 5\n" +
            "up 4\n" +
            "forward 6\n" +
            "forward 7\n" +
            "forward 9\n" +
            "down 3\n" +
            "forward 7\n" +
            "forward 3\n" +
            "down 4\n" +
            "up 4\n" +
            "down 8\n" +
            "forward 6\n" +
            "forward 7\n" +
            "forward 9\n" +
            "forward 4\n" +
            "down 3\n" +
            "up 5\n" +
            "down 7\n" +
            "down 7\n" +
            "forward 9\n";
}
